### ISSUE TITLE
indent-on-paste not work well

### ISSUE THREAD

**Issue by zlzdp** [gazugafan/vscode-indent-on-paste#1]
source:
if (1)
{
	if (2)
	{
		console.log("test");
	}
}

then paste:
            if (1)
      {
        if (2)
        {
          console.log("test");
        }
      }

**[auto insert too more space]**

my config:
"editor.tabSize": 2,
use space tab.

![image](https://user-images.githubusercontent.com/9802845/44137278-5f7c9304-a0a2-11e8-8745-eef7a32a3394.png)

ths.

**Comment by gazugafan** [comment]
I could reproduce problems similar to this, but not consistently. Still, I just released a few improvements that I think might be related to your issue. Can you give v2.2.1 a try?

**Comment by zlzdp** [comment]
I tested it.
the problem not fix.

more details:
press enter key, cursor move to new line,
but vs code auto create intent in the new line,
then paste the code after intent,
the problem will reproduce.


I found a way can skip the problem,(is not a good way)
add setting in vs code:
"trailing-spaces.trimOnSave": true,

operation steps:
press enter key, cursor move to new line,
vs code auto create intent in the new line,
press ctrl + s, intent will delete,
then paste the code after intent,
the code format is good.

so,
the core of problem is: 
if you paste code after intent, can't got good format.

**Comment by zlzdp** [comment]
I hope my feedback can help you, and thank you very much.

**Comment by zlzdp** [comment]
I tested 2.2.1, I paste the code into .vue file [(Vue js Single File Components).](https://vuejs.org/v2/guide/single-file-components.html)
but now, I paste the code into .js file, I got a good format.
maybe my installed extension caused the problem.
do you have any idea for the problem?

**Comment by gazugafan** [comment]
I'm having trouble understanding how to reproduce your problem. Maybe a screen recording of the problem happening would help?

The fact that it's not working in a certain file extension leads me to believe you have something else re-formatting your code on paste. You could try setting indentOnPaste.pasteMethod to "workaround" in your settings file. That will make sure the code doesn't get re-formatted when pasting.

Also, just in case you don't realize it: this extension doesn't attempt to re-format your code in any way. It just adjusts the indentation level of your clipboard to match the position you're pasting at. So, don't expect to copy something like...
```
if (1)
{
console.log('test');
}
```
... and have it re-formatted to something like this on paste...
```
if (1)
{
    console.log('test');
}
```
... you would need an extension that re-formats your code to do that. Typically those are language-specific. So, if that's what you're hoping to achieve, you might need to find a Vue extension that can re-format the HTML, CSS, and JS in .vue files.
