### ISSUE TITLE
[Swift] Paste after a blank line doesn't re-indent.

### ISSUE THREAD

**Issue by pappy74** [gazugafan/vscode-indent-on-paste#17]
_Original_
```
print("hi!")

if true {
  doSomething()
}
```

If I copy the `doSomething()` line to directly below the `print`, it works.
```
print("hi!")
doSomething()

if true {
  doSomething()
}
```

But, if I paste the line after the newline, it retains the original indentation.
```
print("hi!")

  doSomething()
if true {
  doSomething()
}
```

**Comment by gazugafan** [comment]
Can't reproduce. Have any other info? Maybe a conflicting extension? You could try setting the `paste method` setting to `workaround` to be sure there's no other language server formatting going on.

![screen-capture](https://user-images.githubusercontent.com/854538/96180617-51ae7c80-0ef8-11eb-8f1a-9e13cd5c9911.gif)
