### ISSUE TITLE
Pasting does not work after installing this extension

### ISSUE THREAD

**Issue by tankirules** [gazugafan/vscode-indent-on-paste#18]
I am in a remote workspace, after enabling this extension, ctrl +v or using right click -> paste will paste nothing.

**Comment by gazugafan** [comment]
I can't reproduce this, but it sounds similar to #3 #7 and #12

In these, the problem was that the `xsel` binary wasn't set to be executable under Linux. Maybe check that to start? You should find this file where this extension is installed, under `node_modules/clipboardy/fallbacks/linux`
