### ISSUE TITLE
Pasting UTF-8 Chars results in a string of ? characters

### ISSUE THREAD

**Issue by renodubois** [gazugafan/vscode-indent-on-paste#2]
Running Indent on Paste version 2.2.1, VS:Code version 1.28.2, macOS 10.14.

I assume this affects most UTF-8 chars, but I was seeing it while trying to paste this string:
```
От кого
```

Pasting that into a different file w/ the extension enabled resulted in the following string:
```
?? ????
```

**Comment by gazugafan** [comment]
Seems to be working for me on Windows 10, at least. Doing a little research leads me to these...
https://github.com/goessner/mdmath/issues/13
https://github.com/telesoho/vscode-markdown-paste-image/issues/10
... I wonder if switching from node-copy-paste to clipboardy will solve the problem for you. I'll try it out and hopefully release an update soon!

**Comment by renodubois** [comment]
Awesome, thanks a bunch!

**Comment by gazugafan** [comment]
Okay! Switching to clipboardy wasn't a huge deal. Pasting UTF8 characters is still working like normal on Windows, but I don't have a Mac around to test to see if it fixes your issue. Can you give v2.3.0 a try and report back?

**Comment by gazugafan** [comment]
... actually, it'll be v2.3.1 (just forgot to update the README)

**Comment by renodubois** [comment]
Sorry for the late response, looks like it's working again! Thanks again for the fix.
