### ISSUE TITLE
Add paste command and prevent native paste hijack option

### ISSUE THREAD

**Issue by gazugafan** [gazugafan/vscode-indent-on-paste#5]
Requested by @Galzor
https://github.com/gazugafan/vscode-indent-on-paste/issues/3#issuecomment-489091857

**Comment by Amanpeet** [comment]
yes please, it will solve almost all of the issues which this plugin is facing right now.

**Comment by gazugafan** [comment]
A fix for the WSL problem is incoming. I've decided against adding a paste command, as you can always sidestep the extension using CTRL+SHIFT+V.
