### ISSUE TITLE
Multicursor problems

### ISSUE THREAD

**Issue by gazugafan** [gazugafan/vscode-indent-on-paste#6]
Pasting with multiple cursors or selections doesn't seem to work right. It only pastes to the first cursor/selection. Not sure what can be done about this. You would think calling the native paste command should work correctly, but it apparently doesn't.

Could re-implement multi-cursor paste functionality, but this would need to circumvent the native paste command (using the workaround paste method), which isn't ideal.

Should explore other options. Are the multi-cursors/selections being altered inadvertently somehow? Maybe raise an issue with VS Code itself?

Raised by @Galzor
https://github.com/gazugafan/vscode-indent-on-paste/issues/3#issuecomment-489091857

**Comment by Amanpeet** [comment]
or you can just remove the plugin's functionality while multicursor is active.
like users wont be expecting the formating etc while pasting at multiple places.

**Comment by gazugafan** [comment]
Should be fixed by https://github.com/gazugafan/vscode-indent-on-paste/pull/9

Report back if this is still a problem in v2.3.4. Thanks @albertmir!
