### ISSUE TITLE
Unable to paste within remote workspace (WSL or ssh)

### ISSUE THREAD

**Issue by ahobsonsayers** [gazugafan/vscode-indent-on-paste#7]
I love this plugin, but unfortunately I have to disable it when using a remote workspace like on WSL or ssh because it prevents me from pasting. 

The plugin is appropriately installed on the remote.

Any help is much appreciated

**Comment by gazugafan** [comment]
Strange! I'm guessing it must be your local machine that is storing clipboard content. So when you paste, the remote machine doesn't actually have anything on its clipboard. The plugin then intercepts the paste command, but there's nothing on the remote machine's clipboard, so nothing happens. Or maybe something with the timing of how the remote machine's clipboard gets updated? Something like that!

I think once I add the format and paste command in issue #5 you should be able to use that instead to workaround this problem. I don't really use this anymore, though, and haven't had time to work on it lately. In the meantime, maybe look into a clipboard sync option in your remote connection app? Let me know if you find anything!

**Comment by ahobsonsayers** [comment]
Hey! Sorry for the slow reply. Your theory about why it might not be working actually makes a lot of sense and is a reason I hadn't thought about. I will definitely try your clipboard update suggestion.

Out of interest, if you don't use this plugin anymore, what do you use instead? Always in the lookout for good extensions!

**Comment by gazugafan** [comment]
I work mostly with PHP and almost always use PHPStorm as my IDE now. If I still did PHP in VS Code, I'd still probably be using this extension. Usually when I use VS Code, though, it's for a language that already has better built-in formatting support like TypeScript or C#, so that more-or-less defeats the purpose of this extension. The formatting available for PHP in VS Code isn't configurable and doesn't really fit closely with my preferences, unfortunately, which is why I built this to begin with.

**Comment by copdips** [comment]
Hello,

Same issue here with remote-ssh.
Other indent paste plugins work.
But by googling, I finally find that vscode has already built-in indent option on paste.

**Comment by ahobsonsayers** [comment]
Hey @copdips! Out of interest, where did you find the info that vscode includes indent on paste? Can you share a link? I haven't seen my vscode have this option, so I'd be very interested in anything that might be able to point me in the right direction. Thanks!

**Comment by copdips** [comment]
Maybe I'm wrong, could you please explain what is difference between the built-in indent and the this extension's indent ?

Nevertheless, if I enable this extesion with [VSCode Remove extension](https://code.visualstudio.com/docs/remote/remote-overview), and remote ssh to a redhat 7 server from vscode installed in a windows 10.

The copy past from redhat 7 to windows is ok.
the copy past from windows 10 to redhat 7 is ko.
the copy past from redhat 7 to redhat 7 is ko.

![image](https://user-images.githubusercontent.com/13083856/67150923-42cdc380-f2be-11e9-9fea-fc324062f95c.png)

**Comment by gazugafan** [comment]
For VS Code's built-in auto-indent to work, you need to install a language server extension for whatever language you're working in. Any indentation rules would then be defined in that language server extension. My extension is language-agnostic, and sidesteps the language server system entirely. It can actually work in tandem with a language server extension, if you like.

**Comment by CodeBrotha** [comment]
Any solution for this problem yet?

**Comment by gazugafan** [comment]
Not yet, and probably not anytime soon unfortunately. Feel free to take a crack at it and a send a PR if you figure it out!

**Comment by oagix** [comment]
I'm having the same issue on a remote SSH environment.

**Comment by gazugafan** [comment]
This should finally be fixed in 2.4.0 just released! It was actually a problem with the clipboardy dependency trying to use xsel in WSL instead of the Windows executable. Let me know if any of you still have trouble after updating to 2.4.0.

**Comment by ahobsonsayers** [comment]
Thanks so much! I don't currently use WSL (now develop exclusively in Linux) but I will give it a test when im next on windows!
